### ISSUE TITLE
RSS Autodiscovery, type is atom+xml not rss+xml

### ISSUE THREAD

**Issue by Enselic** [snaptortoise/jekyll-rss-feeds#23]
In https://github.com/snaptortoise/jekyll-rss-feeds/blob/master/README.md under **RSS Autodiscovery** it says type="application/**atom**+xml" but it should be type="application/**rss**+xml" according to the linked to spec, namely http://www.rssboard.org/rss-autodiscovery

**Comment by georgemandis** [comment]
Nice catch! That's been sitting there for a while...
