### ISSUE TITLE
Include entire post (not just excerpt) for feed.category.xml

### ISSUE THREAD

**Issue by jrosen48** [snaptortoise/jekyll-rss-feeds#25]
I'm using the `feed.category.xml` file to generate a feed for posts for a specific category. It works great, but only includes an excerpt, rather than the entire post. Is it possible to modify the `.xml` file to include the entire post?

**Comment by georgemandis** [comment]
The way it's setup it should only use the `excerpt` if it's specified in the front-matter:

```
{% if post.excerpt %}
    <description>{{ post.excerpt | xml_escape }}</description>
{% else %}
    <description>{{ post.content | xml_escape }}</description>
{% endif %}
```

If you need to have the `excerpt` metadata specified in your front-matter but don't want it included in your feed you could simply replace this whole block with:

```<description>{{ post.content | xml_escape }}</description>```

I'm inclined to leave the repo the way it is, but hopefully that helps!

**Comment by jrosen48** [comment]
Thanks so much, this sounds good, one question from a Jekyll and XML novice.

Maybe I'm conflating two things. I noticed in a feed reader that the excerpt appeared - can adding something like the following:

    <content>{{ post.content | xml_escape }}</content>

Make it so that the whole post appears?

thanks again

**Comment by georgemandis** [comment]
If you replace the whole block with that snippet it should make the whole post appear. If your goal is to have the entire post appear in the feed there really isn't another way in this situation, unless I'm  misunderstanding your question? 

:)

**Comment by jrosen48** [comment]
Thanks so much for your response.

Sorry, this may branching into not `jekyll-rss-feeds`-land.

So, when I subscribe to`jekyll-rss-feeds` this category feed generated through the `feed.category.xml` file: (https://jrosen48.github.io/feed.category.xml)[https://jrosen48.github.io/feed.category.xml]

This appears in Feedly--_just the first paragraph_:

<blockquote class="imgur-embed-pub" lang="en" data-id="a/dJMXs"><a href="//imgur.com/dJMXs"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

But, when I subscribe to this feed generated, if I understand correctly, through the `jekyll-feed` plugin: (https://jrosen48.github.io/feed.xml)[https://jrosen48.github.io/feed.xml]

This appears in Feedly--_the entire post_:

<blockquote class="imgur-embed-pub" lang="en" data-id="a/O50p7"><a href="//imgur.com/O50p7"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by georgemandis** [comment]
Hmm.  That does seem odd. I'm not familiar with Feedly, but my only thought might be the Feedly caches the feeds? If you try subscribing and resubscribing or maybe adding something like `?v1` to the end of the the URL (https://jrosen48.github.io/feed.category.xml?v1) maybe it'll stop looking at cache? You might also want to try writing a new post in that category to see if it works.

I think it's something related to that because the XML isn't that complicated and I'm not sure what else it could be. It looks rights!

**Comment by jrosen48** [comment]
Ah hah! Adding `?v1` did the trick; you must be right that Feedly may be caching the feeds; suscribing and resubscribing didn't do the trick, but adding that to the URL did.

Thanks again
