### ISSUE TITLE
Add Pages Template

### ISSUE THREAD

**Issue by jhabdas** [snaptortoise/jekyll-rss-feeds#27]
Output pages using `site.html_pages` to prevent `txt` files from outputting and XML with embedded XSLT templates from attempting to be transformed.

http://jekyllrb.com/docs/variables/

**Comment by georgemandis** [comment]
I wasn't aware of that variable! I'm assuming that this would return pages, blog posts and other collection content from the Jekyll site? Or does it exclude posts and collection content? I haven't had a chance to test it and it's unclear to me from the documentation.

Thanks!

**Comment by jhabdas** [comment]
I'm working on a Prototype right now I'll drop you the template when I finish just don't let me forget!

**Comment by georgemandis** [comment]
Sounds good. Thanks! When it's done and the pull request goes through please consider submitting a similar change for my jekyll-json-feed project.

**Comment by jhabdas** [comment]
Bad news to share. When used on a medium complexity site it actually causes liquid to spill into the feed. As a result I have nothing to share I would feel comfortable sharing. To reproduce the funky liquid not rendering behavior please see the following instructions: https://github.com/Phlow/feeling-responsive/issues/151

Spent a few hours on it and, unfortunately, liquid output to the feed is a showstopper for me. Closing issue as a result. Please feel free to reopen.

**Comment by jhabdas** [comment]
Got page feeds working wonderfully with `jekyll-feed` by the way. If doing this be sure to scrub your output for sensitive files such as `.well-known/acme-challenge/qXWXT3LE-/index.html`.

**Comment by georgemandis** [comment]
To clarify, you're saying Liquid spills into the feed when you use `site.html_pages` instead of `site.pages` or `site.posts`? How odd! Must be an issue with Jekyll.

I haven't tried to recreate it but will take a look when I have time. Thanks for trying!

**Comment by jhabdas** [comment]
Seemed it was a Jekyll issue. It's an edge or corner case though, as it doesn't happen out of the box. In my case I was using Jekyll 3.3.1 and seeing unprocessed liquid output in my RSS feed on a medium-sized site when looping over `site.html_pages`.

In this case a medium site means:

- About 10 pages made of files ending in `html` and `md`
- Liberal of `_data` within templates
- About 25 includes to build pages and posts
- 6 blog posts, ~50,000 words each
- 5 collections with a combined total of ~230 items
- A good amount of blob data in `_uploads`

I wasn't able to isolate the specific area where the edge case was occurring. But the site used very few plugins and none related to feeds until I pulled in `jekyll-feed` to take care of business.
